apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: {{ .Values.csi.secretProviderClassName }}
  namespace: {{ .Release.Namespace }}
spec:
  provider: aws
  secretObjects:
  - secretName: mysql-secret
    type: Opaque
    data:
    - objectName: MYSQL_ROOT_PASSWORD
      key: password
    - objectName: MYSQL_DATABASE
      key: database
  parameters:
    objects: |
{{ .Values.csi.parameters.objects | indent 6 }}
