replicaCount: 2

image:
  repository: 960341592570.dkr.ecr.us-east-1.amazonaws.com/task1-dev-us-east-1-daniel-katsenyuk-nginx-repo
  tag: "1.0.0"


service:
  type: ClusterIP
  port: 80

backend:
  serviceName: "application-service"
  namespace: "application"
  port: 5000