apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: app-parameter-provider
  namespace: application
spec:
  provider: aws
  secretObjects:
  - secretName: app-secret
    type: Opaque
    data:
    - objectName: MYSQL_HOST
      key: host
    - objectName: MYSQL_USER
      key: user
    - objectName: MYSQL_PASSWORD
      key: password
    - objectName: MYSQL_DATABASE
      key: database
    - objectName: APP_TOKEN
      key: token
  parameters:
    objects: |
      - objectName: "/dev/myapp/mysql/host"
        objectType: "ssmparameter"
        objectAlias: "MYSQL_HOST"
      - objectName: "/dev/myapp/mysql/user"
        objectType: "ssmparameter"
        objectAlias: "MYSQL_USER"
      - objectName: "/dev/myapp/mysql/password"
        objectType: "ssmparameter"
        objectAlias: "MYSQL_PASSWORD"
      - objectName: "/dev/myapp/mysql/database"
        objectType: "ssmparameter"
        objectAlias: "MYSQL_DATABASE"
      - objectName: "task1-dev-us-east-1-daniel-katsenyuk-generated-token"
        objectType: "secretsmanager"
        objectAlias: "APP_TOKEN"