apiVersion: v1
kind: ServiceAccount
metadata:
  name: mysql-sa
  namespace: mysql
  annotations:
    eks.amazonaws.com/role-arn: "arn:aws:iam::960341592570:role/task1-dev-us-east-1-daniel-katsenyuk-mysql-role"

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-deployment
  namespace: mysql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      serviceAccountName: mysql-sa
      containers:
      - name: mysql
        image: mysql:8.0
        securityContext:
          runAsUser: 999 
        ports:
        - containerPort: 3306
        env: 
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: password
        - name: MYSQL_DATABASE
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: database
        volumeMounts: 
        - name: efs-storage
          mountPath: /var/lib/mysql 
        - name: secrets-store-inline
          mountPath: "/mnt/secrets-store"
          readOnly: true
      volumes:
      - name: efs-storage
        persistentVolumeClaim:
          claimName: efs-mysql-claim 
      - name: secrets-store-inline
        csi:
          driver: secrets-store.csi.k8s.io
          readOnly: true
          volumeAttributes:
            secretProviderClass: "mysql-parameter-provider"

---
apiVersion: v1
kind: Service
metadata:
  name: mysql-service
  namespace: mysql
spec:
  selector:
    app: mysql
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306