apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: efs-sc
provisioner: efs.csi.aws.com
parameters:
  provisioningMode: efs-ap
  fileSystemId: fs-0b9ebcb800eec5bc9 
  directoryPerms: "700"
  uid: "999" 
  gid: "999"

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: efs-mysql-claim
  namespace: mysql
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: efs-sc
  resources:
    requests:
      storage: 5Gi