apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: {{ .Values.csi.secretProviderClassName }}
  namespace: {{ .Release.Namespace }}
spec:
  provider: aws
  secretObjects:
  - secretName: app-secret
    type: Opaque
    data:
    - objectName: MYSQL_HOST
      key: host
    - objectName: MYSQL_USER
      key: user
    - objectName: MYSQL_PASSWORD
      key: password
    - objectName: MYSQL_DATABASE
      key: database
    - objectName: APP_TOKEN
      key: token
  parameters:
    objects: |
{{ .Values.csi.parameters.objects | indent 6 }}
